name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Checking out repo
      if: github.event.action == 'issue_comment'
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.client_payload.repository.full_name}}
        ref: master 

    - name: Printing stuff
      run: |
        echo "Workflow triggered on PR comment"
        echo ***********************
        echo "Repo Name: ${{github.event.client_payload.repository.full_name}}"
        echo ***********************
        echo ${{github.event.client_payload.comment.body}}
        echo ***********************
        echo "Name of the current branch: ${GITHUB_REF##*/}"
        echo ***********************
        echo "Sha commit name: ${GITHUB_SHA}"

