name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Printing hello
      #if: github.event.action == 'issue_comment'
      run: |
        echo "Workflow triggered on PR comment"
        echo 2
        echo ${{github.event.action}}
        echo 3
        echo ${{github.event}}
        echo 4
        echo ${{github.event.issue.url}}
        echo 5
        echo ${{data.client_payload}}
        echo 6
        echo ${{data.event_type}}
        echo 7
        echo ${{event.github.payload}}