name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Printing hello
      #if: github.event.action == 'issue_comment'
      uses: actions/checkout@v1
      with:
        repository: ${{github.event.client_payload.repository.full_name}}
      run: |
        echo "Workflow triggered on PR comment"
        echo ***********************
        echo ${{github.event.client_payload.comment.body}}
        echo "Name of the current branch: ${GITHUB_REF##*/}"
        echo "The sha: ${GITHUB_SHA}"
        echo "The repo: ${GITHUB_REPOSITORY}"

