name: Webhook Example
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Checking out repo
      if: github.event.action == 'issue_comment'
      uses: actions/checkout@v2
      with:
        repository: ${{github.event.client_payload.repository.full_name}}
        ref: master

    - name: Printing stuff
      run: |
        echo "Comment made is : ---------${{github.event.client_payload.comment.body}}"
        echo "Person who made the comment--------------${{github.event.client_payload.comment.author_association}}"
        echo "Name of the current branch-------- ${GITHUB_REF##*/}"

    - name: Using backport action
      uses: TestOrgWeb/infra/actions@master
      with:
        branchName: ${{github.event.client_payload.repository.full_name}}

